/*
		A basic implementation of the JDialog class.
*/

import java.awt.*;
import javax.swing.*;

public class JLoginDialog extends javax.swing.JDialog
{
    Frame myParent;
    public boolean _bCancel;
    
	public JLoginDialog(Frame parent)
	{
		super(parent);
	    myParent = parent;
		_bCancel = true;
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Login to a PEOS sever");
		getContentPane().setLayout(null);
		setSize(329,256);
		setVisible(false);
		JHostLabel.setText("Host Name:");
		getContentPane().add(JHostLabel);
		JHostLabel.setBounds(36,36,84,24);
		JPortLabel.setText("Port:");
		getContentPane().add(JPortLabel);
		JPortLabel.setBounds(36,72,84,24);
		JLoginLabel.setText("Login:");
		getContentPane().add(JLoginLabel);
		JLoginLabel.setBounds(36,108,84,24);
		JPasswordLabel.setText("Password:");
		getContentPane().add(JPasswordLabel);
		JPasswordLabel.setBounds(36,144,84,24);
		getContentPane().add(JHostTextField);
		JHostTextField.setBounds(120,36,168,24);
		getContentPane().add(JPortTextField);
		JPortTextField.setBounds(120,72,168,24);
		getContentPane().add(JLoginTextField);
		JLoginTextField.setBounds(120,108,168,24);
		JCancelButton.setText("Cancel");
		JCancelButton.setActionCommand("Cancel");
		JCancelButton.setMnemonic((int)'C');
		getContentPane().add(JCancelButton);
		JCancelButton.setBounds(182,204,84,24);
		getContentPane().add(JPWPasswordField);
		JPWPasswordField.setBounds(120,144,168,24);
		JLoginButton.setText("Login");
		JLoginButton.setActionCommand("Login");
		JLoginButton.setMnemonic((int)'L');
		getContentPane().add(JLoginButton);
		JLoginButton.setBounds(62,204,84,24);
		//}}
	    
	    PEOS_GUI myPEOS = (PEOS_GUI)myParent;
	    if (myPEOS._PEOSInterface != null)
	    {
	        JHostTextField.setText(myPEOS._PEOSInterface.getHost()); 
	        JHostTextField.setEnabled(false);
	        JPortTextField.setText(myPEOS._PEOSInterface.getPort());
	        JPortTextField.setEnabled(false);
	    }
	    
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JLoginButton.addActionListener(lSymAction);
		JCancelButton.addActionListener(lSymAction);
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		//}}
	}

	public JLoginDialog()
	{
		this((Frame)null);
	}

	public JLoginDialog(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new JLoginDialog()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JLabel JHostLabel = new javax.swing.JLabel();
	javax.swing.JLabel JPortLabel = new javax.swing.JLabel();
	javax.swing.JLabel JLoginLabel = new javax.swing.JLabel();
	javax.swing.JLabel JPasswordLabel = new javax.swing.JLabel();
	javax.swing.JTextField JHostTextField = new javax.swing.JTextField();
	javax.swing.JTextField JPortTextField = new javax.swing.JTextField();
	javax.swing.JTextField JLoginTextField = new javax.swing.JTextField();
	javax.swing.JButton JCancelButton = new javax.swing.JButton();
	javax.swing.JPasswordField JPWPasswordField = new javax.swing.JPasswordField();
	javax.swing.JButton JLoginButton = new javax.swing.JButton();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JLoginButton)
				JLoginButton_actionPerformed(event);
			else if (object == JCancelButton)
				JCancelButton_actionPerformed(event);
		}
	}

	void JLoginButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		try {
		    PEOS_GUI myPEOS = (PEOS_GUI)myParent;
	        if ( myPEOS._PEOSInterface == null)
		    {
		        int port = Integer.parseInt(this.JPortTextField.getText());
        	    myPEOS._PEOSInterface = new PEOS_Interface(this.JHostTextField.getText(), port);
        	}
		    myPEOS._PEOSInterface.PEOS_login(this.JLoginTextField.getText(), this.JPWPasswordField.getText());
		    _bCancel = false;
			// JAboutDialog Hide the JAboutDialog
			this.setVisible(false);
		} catch (NumberFormatException en) {
			String msg = "Get exception: " + en;
            JOptionPane.showMessageDialog(this, msg, "Number Format",JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			String msg = "Get exception: " + e;
            JOptionPane.showMessageDialog(this, msg, "Login",JOptionPane.ERROR_MESSAGE);
		}
	}

	void JCancelButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		try {
		    _bCancel = true;
			// JAboutDialog Hide the JAboutDialog
			this.setVisible(false);
		} catch (Exception e) {
			String msg = "Get exception: " + e;
            JOptionPane.showMessageDialog(this, msg, "Cancel",JOptionPane.ERROR_MESSAGE);
		}
	}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == JLoginDialog.this)
				JLoginDialog_windowClosing(event);
		}
	}

	void JLoginDialog_windowClosing(java.awt.event.WindowEvent event)
	{
		try {
			// JLoginDialog Hide the JLoginDialog
			this.setVisible(false);
		} catch (Exception e) {
			String msg = "Get exception: " + e;
            JOptionPane.showMessageDialog(this, msg, "Windows Close",JOptionPane.ERROR_MESSAGE);
		}
	}
}