/*
		A basic implementation of the JDialog class.
*/

import java.awt.*;
import javax.swing.*;

public class JLoginDialog extends javax.swing.JDialog
{
	public JLoginDialog(Frame parent)
	{
		super(parent);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Login to a PEOS sever");
		getContentPane().setLayout(null);
		setSize(329,256);
		setVisible(false);
		JHostLabel.setText("Host Name:");
		getContentPane().add(JHostLabel);
		JHostLabel.setBounds(36,36,84,24);
		JPortLabel.setText("Port:");
		getContentPane().add(JPortLabel);
		JPortLabel.setBounds(36,72,84,24);
		JLoginLabel.setText("Login:");
		getContentPane().add(JLoginLabel);
		JLoginLabel.setBounds(36,108,84,24);
		JPasswordLabel.setText("Password:");
		getContentPane().add(JPasswordLabel);
		JPasswordLabel.setBounds(36,144,84,24);
		getContentPane().add(JHostTextField);
		JHostTextField.setBounds(120,36,168,24);
		getContentPane().add(JPortTextField);
		JPortTextField.setBounds(120,72,168,24);
		getContentPane().add(JLoginTextField);
		JLoginTextField.setBounds(120,108,168,24);
		JLoginButton.setText("Login");
		JLoginButton.setMnemonic((int)'L');
		getContentPane().add(JLoginButton);
		JLoginButton.setBounds(62,204,84,24);
		JCaancelButton.setText("Cancel");
		JCaancelButton.setMnemonic((int)'C');
		getContentPane().add(JCaancelButton);
		JCaancelButton.setBounds(182,204,84,24);
		getContentPane().add(JPWPasswordField);
		JPWPasswordField.setBounds(120,144,168,24);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JLoginButton.addActionListener(lSymAction);
		JCaancelButton.addActionListener(lSymAction);
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		//}}
	}

	public JLoginDialog()
	{
		this((Frame)null);
	}

	public JLoginDialog(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new JLoginDialog()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JLabel JHostLabel = new javax.swing.JLabel();
	javax.swing.JLabel JPortLabel = new javax.swing.JLabel();
	javax.swing.JLabel JLoginLabel = new javax.swing.JLabel();
	javax.swing.JLabel JPasswordLabel = new javax.swing.JLabel();
	javax.swing.JTextField JHostTextField = new javax.swing.JTextField();
	javax.swing.JTextField JPortTextField = new javax.swing.JTextField();
	javax.swing.JTextField JLoginTextField = new javax.swing.JTextField();
	javax.swing.JButton JLoginButton = new javax.swing.JButton();
	javax.swing.JButton JCaancelButton = new javax.swing.JButton();
	javax.swing.JPasswordField JPWPasswordField = new javax.swing.JPasswordField();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JLoginButton)
				JLoginButton_actionPerformed(event);
			else if (object == JCaancelButton)
				JCaancelButton_actionPerformed(event);
		}
	}

	void JLoginButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		try {
			// JAboutDialog Hide the JAboutDialog
			this.setVisible(false);
		} catch (Exception e) {
		}
			 
	}

	void JCaancelButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		try {
			// JAboutDialog Hide the JAboutDialog
			this.setVisible(false);
		} catch (Exception e) {
		}
	}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == JLoginDialog.this)
				JLoginDialog_windowClosing(event);
		}
	}

	void JLoginDialog_windowClosing(java.awt.event.WindowEvent event)
	{
		try {
			// JLoginDialog Hide the JLoginDialog
			this.setVisible(false);
		} catch (Exception e) {
		}
	}
}