# PML compiler
PML = ../../bin/compiler

# PML gdbm flags
PMLFLAGS = -f GDBM

# PML raw source
PMLSRC = milestone1.pml \
         milestone5.pml \
         checkin.pml \
         checkout.pml \
         make.pml \
         updateANDresolve.pml 

# PML compilation
PMLGCODE:  ${PMLSRC} 
	${PML} ${PMLFLAGS} ${PMLSRC}

