#PML compiler
PML = ../../compiler/compiler

#PML flags
PMLFLAGS = 

#PML raw source
PMLRSRC = milestone1.pml 

#PML gdbm source
PMLGSRC = milestone1.gdbm

#Instructions
PMLCODE : ${PMLGSRC}
          ${PML} ${PMLFLAGS} ${PMLRSRC}

