/*
 * File: Traverse.c
 * Traverse graph built by parser, printing nodes visited.
 * $ID$
 * Author: John Noll & Jigar Shah
 * Date Written: Aug 10 2003
 * Date Last Modified: Aug 11 2003
 *
 */

# include <stdio.h>
# include <errno.h>
# include <stdlib.h>
# include <string.h>
# include <unistd.h>
# include "scanner.h"
# include "parser.h"
# include "tokens.h"

/* Provide main with a prototype to eliminate compiler warnings. */

extern int main (
# ifdef ANSI_PROTOTYPES
    int		/* argc */,
    String []	/* argv */
# endif
);

/*
 * This function goes through all the nodes in the graph generated by the parser and prints  * out the name, type, predecessors, successors, matching, dominator values for that node in * the graph.
 *
 */
  

void traverse(Node n)
{
  while(n != NULL)
   {
    if (n) {
	int i;
        Node child;
        Node parent;
	printf("Node Name : %s\n", n->name? n->name:"(empty)");
        printf("Node Type: %d\n",n->type);
       // printf("Node Status: %s\n",STATUS(n));
       // printf("Node Marked: %d\n",MARKED(n));
	for (i = 0; (child = (Node) ListIndex(n->successors, i)); i++) 
         {
        printf("Successor of %s: %s\n",n->name,child->name? child->name:"(empty)");
         }

        for (i=0; (parent = (Node) ListIndex(n->predecessors,i)); i++)
         {
        printf("Predecessor of %s: %s\n",n->name,parent->name? parent->name:"(empty)");  
         }

        if(n->dominator != NULL)
        printf("Dominator of %s: %s\n",n->name,n->dominator->name? n->dominator->name:"(empty)");
        else
        printf("No Dominator \n");

        if(n->matching != NULL)       
        printf("Matching of %s: %s\n",n->name,n->matching->name? n->matching->name:"(empty)");
        else
        printf("No Matching \n");

       } //if

       n = n->next;

   } // while
} // traverse



int main (argc, argv)
    int    argc;
    String argv [ ];
{
    int status;

    filename = "-";
    status = EXIT_SUCCESS;

    do {
	if (optind < argc) {
	    filename = argv [optind];
	    lineno = 1;
	}

	if (strcmp (filename, "-") == 0) {
	    filename = "stdin";
	    yyin = stdin;

	    if (yyparse ( ))
		status = EXIT_FAILURE;

	} else if ((yyin = fopen (filename, "r")) != NULL) {
	    if (yyparse ( ))
		status = EXIT_FAILURE;

	    fclose (yyin);

	} else {
	    fprintf (stderr, "%s: ", argv [0]);
	    perror (filename);
	    status = EXIT_FAILURE;
	}

    } while (++ optind < argc);

    if (status != EXIT_FAILURE) {
	if (program) {
	    traverse(program->source);
	}
    }
    exit (status);
}
