# Where the cgi programs get installed.
IMAGES = peos_logo.jpg done_button.jpg suspend_button.jpg \
	perform_button.jpg back_button.jpg newprocess_button.jpg
install: 
	cp $(IMAGES) $(INSTALL_DIR)/images
	chmod a+r $(INSTALL_DIR)/images/*.jpg

