#######################################################################
## File Information: $Id: uiErrorHandler.tcl,v 1.2 1999/05/07 18:53:09 jneuder Exp $
#######################################################################


#######################################################################
# Namespace name: ::uiErrorHandler
# Description: This attempts to handles errors generated by the PML
# User Interface or Received by the PML Engine daemon
#######################################################################

package provide uiErrorHandler

namespace eval ::uiErrorHandler:: {
     namespace export SendMsg
}

#######################################################################
# Function name:  ::uiEngHandler::SendMsg
# Precondition:	  an error has occurred.
# Postcondition:  An error pop-up is generated an a response returned.
# Description:	 Generates an error dialog box displaying the string
#		 contained in the errorMsg variable.
# Arguments:	  errorMsg -->	Error Message to be displayed
#######################################################################
proc ::uiErrorHandler::SendMsg { errorMsg } {

    set ::uiValues::errorResponse [tk_messageBox -parent . \
			    -title "PML Error" -type yesno \
			    -icon error -message $errorMsg]

#
#
# Goto back to Login Screen or send login message to Engine.
#
#
}

