#
# This makefile generates the EIUnitTest
#
 
#
# The java 
#
JAVA_HOME=/usr/local/java/jdk1.2.2
JAVAC=${JAVA_HOME}/bin/javac

#
# The application
#
APP_LIB=../../../../share/java

all:
#	rm *.class
	${JAVAC} -classpath $(APP_LIB) *.java
