/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "interface.h"
static GtkWidget *delete1;
static GtkWidget *view;

GtkWidget*
create_Peos (void)
{
  GtkWidget *menubar;
  guint tmp_key;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *create;
  GtkWidget *separator;
  GtkWidget *exit1;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkAccelGroup *help_menu_accels;
  GtkWidget *about;

  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();
  
  Peos = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Peos, "Peos");
  gtk_object_set_data (GTK_OBJECT (Peos), "Peos", Peos);
  gtk_window_set_title (GTK_WINDOW (Peos), _("Peos"));
  gtk_window_set_default_size (GTK_WINDOW (Peos), 800, 640);
  gtk_widget_realize (Peos);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_ref (vbox);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "vbox", vbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (Peos), vbox);

  menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar, "menubar");
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox), menubar, FALSE, TRUE, 0);

  file = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (file, "file");
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_set_name (file_menu, "file_menu");
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  create = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (create)->child),
                                   _("_Create"));
  gtk_widget_add_accelerator (create, "activate_item", file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (create, "create");
  gtk_widget_ref (create);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "create", create,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (create);
  gtk_container_add (GTK_CONTAINER (file_menu), create);
  gtk_tooltips_set_tip (tooltips, create, _("Create A New Process"), NULL);
  gtk_widget_add_accelerator (create, "activate", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  delete1 = gtk_menu_item_new_with_label ("Delete");
/*
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (delete1)->child),
                                   _("_Delete"));
  gtk_widget_add_accelerator (delete1, "activate_item", file_menu_accels,
                              tmp_key, 0, 0);
*/
  gtk_widget_set_name (delete1, "delete");
  gtk_widget_ref (delete1);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "delete", delete1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete1);
  /*************************** DELETE MENU *********************************/
  delmenu = del_menu();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (delete1), delmenu);
  gtk_menu_item_set_placement (GTK_MENU_ITEM (delete1), GTK_LEFT_RIGHT);
  /************************* DELETE MENU ***********************************/

  gtk_container_add (GTK_CONTAINER (file_menu), delete1);
  gtk_tooltips_set_tip (tooltips, delete1, _("Delete A Process"), NULL);
/*
  gtk_widget_add_accelerator (delete1, "activate", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                             GTK_ACCEL_VISIBLE);
*/
  separator = gtk_menu_item_new ();
  gtk_widget_set_name (separator, "separator");
  gtk_widget_ref (separator);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "separator", separator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator);
  gtk_container_add (GTK_CONTAINER (file_menu), separator);
  gtk_widget_set_sensitive (separator, FALSE);

  exit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit1)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (exit1, "activate_item", file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file_menu), exit1);
  gtk_tooltips_set_tip (tooltips, exit1, _("Quit Peos"), NULL);
  gtk_widget_add_accelerator (exit1, "activate", accel_group,
                              GDK_X, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  view = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (view)->child),
                                   _("_View"));
  gtk_widget_add_accelerator (view, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (view, "view");
  gtk_widget_ref (view);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "view", view,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view);
  /***********************************VIEWMENU*****************************************/
  viewmenu = make_menu();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view), viewmenu);
  /**********************************VIEWMENU*****************************************/
  gtk_container_add (GTK_CONTAINER (menubar), view);


  help = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (help, "help");
  gtk_widget_ref (help);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "help", help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar), help);

  help_menu = gtk_menu_new ();
  gtk_widget_set_name (help_menu, "help_menu");
  gtk_widget_ref (help_menu);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "help_menu", help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);
  help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menu));

  about = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about)->child),
                                   _("_About"));
  gtk_widget_add_accelerator (about, "activate_item", help_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (about, "about");
  gtk_widget_ref (about);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "about", about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);
  gtk_tooltips_set_tip (tooltips, about, _("Information"), NULL);
  gtk_widget_add_accelerator (about, "activate", accel_group,
                              GDK_A, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  notebook = create_notebook();
  gtk_widget_set_name (notebook, "notebook");
  gtk_widget_ref (notebook);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "notebook", notebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook);
  
  gtk_container_add (GTK_CONTAINER (vbox), notebook);

  gtk_signal_connect (GTK_OBJECT (Peos), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (create), "activate",
                      GTK_SIGNAL_FUNC (on_create_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (delete1), "activate",
                      GTK_SIGNAL_FUNC (on_delete_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "activate",
                      GTK_SIGNAL_FUNC (on_view_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about), "activate",
                      GTK_SIGNAL_FUNC (on_about_activate),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (Peos), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (Peos), accel_group);
  gtk_accel_group_lock (accel_group);
  gtk_accel_group_lock (file_menu_accels);

  return Peos;
}

GtkWidget*
create_fileselection (void)
{
  GtkWidget *fileselection;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkWidget *file_list;

  fileselection = gtk_file_selection_new (_("Select File"));
  gtk_widget_set_name (fileselection, "fileselection");
  gtk_object_set_data (GTK_OBJECT (fileselection), "fileselection", fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection), 10);

  file_list = GTK_FILE_SELECTION (fileselection)->file_list;
  filter (file_list);
  //gtk_file_selection_complete (GTK_FILE_SELECTION (fileselection), "*.pml");
  ok_button1 = GTK_FILE_SELECTION (fileselection)->ok_button;
  gtk_widget_set_name (ok_button1, "ok_button1");
  gtk_object_set_data (GTK_OBJECT (fileselection), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);
  cancel_button1 = GTK_FILE_SELECTION (fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button1, "cancel_button1");
  gtk_object_set_data (GTK_OBJECT (fileselection), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fileselection_clicked),
                      fileselection);

  gtk_signal_connect_object (GTK_OBJECT (ok_button1), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (fileselection));

  gtk_signal_connect_object (GTK_OBJECT (cancel_button1), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (fileselection));

  gtk_signal_connect (GTK_OBJECT (GTK_FILE_SELECTION (fileselection)->file_list), 
			"select_row", (GtkSignalFunc) filter, fileselection);

  return fileselection;
}

GtkWidget*
create_deletedialog (gchar *string)
{
  GtkWidget *deletedialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *label1;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *OK_delete;
  GtkWidget *Cancel_delete;
  gchar *message;

  if (del_cmd != NULL) {
	free(del_cmd);
	del_cmd = NULL;
  }


  if (!del_cmd) del_cmd = malloc (strlen (exec_path) + 35);
  sprintf (del_cmd, "%s -d %d ", exec_path, atoi (string));

  message = malloc (sizeof (char) * (strlen (string) + 64));
  strcpy (message, "Are you sure you want to delete Process ");
  strcat (message, string); 
  strcat (message, " ? ");

  deletedialog = gtk_dialog_new ();
  gtk_widget_set_name (deletedialog, "deletedialog");
  gtk_object_set_data (GTK_OBJECT (deletedialog), "deletedialog", deletedialog);
  gtk_window_set_title (GTK_WINDOW (deletedialog), _("DELETE"));
  gtk_window_set_policy (GTK_WINDOW (deletedialog), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (deletedialog)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (deletedialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label1 = gtk_label_new (_(message));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (deletedialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label1, TRUE, TRUE, 0);

  dialog_action_area1 = GTK_DIALOG (deletedialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (deletedialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (deletedialog), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  OK_delete = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (OK_delete, "OK_delete");
  gtk_widget_ref (OK_delete);
  gtk_object_set_data_full (GTK_OBJECT (deletedialog), "OK_delete", OK_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OK_delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), OK_delete);
  GTK_WIDGET_SET_FLAGS (OK_delete, GTK_CAN_DEFAULT);

  Cancel_delete = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_set_name (Cancel_delete, "Cancel_delete");
  gtk_widget_ref (Cancel_delete);
  gtk_object_set_data_full (GTK_OBJECT (deletedialog), "Cancel_delete", Cancel_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Cancel_delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), Cancel_delete);
  GTK_WIDGET_SET_FLAGS (Cancel_delete, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (OK_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_delete_clicked),
                      NULL);

  gtk_signal_connect_object (GTK_OBJECT (OK_delete), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (deletedialog));

  gtk_signal_connect_object (GTK_OBJECT (Cancel_delete), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (deletedialog));
  free (message);
  return deletedialog;
}

GtkWidget*
create_exitdialog (void)
{
  GtkWidget *exitdialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *label1;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *OK_quit;
  GtkWidget *Cancel_quit;

  exitdialog = gtk_dialog_new ();
  gtk_widget_set_name (exitdialog, "exitdialog");
  gtk_object_set_data (GTK_OBJECT (exitdialog), "exitdialog", exitdialog);
  gtk_window_set_title (GTK_WINDOW (exitdialog), _("Exit"));
  gtk_window_set_policy (GTK_WINDOW (exitdialog), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (exitdialog)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (exitdialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label1 = gtk_label_new (_("Are You Sure You Want To Quit?"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (exitdialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label1, TRUE, TRUE, 0);

  dialog_action_area1 = GTK_DIALOG (exitdialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (exitdialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (exitdialog), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  OK_quit = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (OK_quit, "OK_quit");
  gtk_widget_ref (OK_quit);
  gtk_object_set_data_full (GTK_OBJECT (exitdialog), "OK_quit", OK_quit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OK_quit);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), OK_quit);
  GTK_WIDGET_SET_FLAGS (OK_quit, GTK_CAN_DEFAULT);

  Cancel_quit = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_set_name (Cancel_quit, "Cancel_quit");
  gtk_widget_ref (Cancel_quit);
  gtk_object_set_data_full (GTK_OBJECT (exitdialog), "Cancel_quit", Cancel_quit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Cancel_quit);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), Cancel_quit);
  GTK_WIDGET_SET_FLAGS (Cancel_quit, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (OK_quit), "clicked",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (Cancel_quit), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (exitdialog));

  return exitdialog;
}

GtkWidget*
create_errordialog (void)
{
  GtkWidget *errordialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *scrolledwindow4;
  GtkWidget *text2;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *OK;
  char buf[MAX_BUF];
  int errorfd;

  errorfd = open ("message", O_RDONLY);
  read (errorfd, buf, MAX_BUF);
  close (errorfd);

  errordialog = gtk_dialog_new ();
  gtk_widget_set_name (errordialog, "errordialog");
  gtk_object_set_data (GTK_OBJECT (errordialog), "errordialog", errordialog);
  gtk_window_set_title (GTK_WINDOW (errordialog), _("Error"));
  GTK_WINDOW (errordialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_policy (GTK_WINDOW (errordialog), TRUE, TRUE, FALSE);

  dialog_vbox2 = GTK_DIALOG (errordialog)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_object_set_data (GTK_OBJECT (errordialog), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (errordialog), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), scrolledwindow4, TRUE, TRUE, 0);
  gtk_widget_set_usize (scrolledwindow4, 300, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  text2 = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (text2, "text2");
  gtk_widget_ref (text2);
  gtk_object_set_data_full (GTK_OBJECT (errordialog), "text2", text2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), text2);
  gtk_text_insert (GTK_TEXT (text2), NULL, NULL, NULL,
                   _("Error: "), -1);

  gtk_text_insert (GTK_TEXT (text2), NULL, NULL, NULL,
                   _(buf), -1);

  dialog_action_area2 = GTK_DIALOG (errordialog)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_object_set_data (GTK_OBJECT (errordialog), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (errordialog), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);

  OK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (OK, "OK");
  gtk_widget_ref (OK);
  gtk_object_set_data_full (GTK_OBJECT (errordialog), "OK", OK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), OK);
  GTK_WIDGET_SET_FLAGS (OK, GTK_CAN_DEFAULT);

  gtk_signal_connect_object (GTK_OBJECT (OK), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (errordialog));

  return errordialog;
}

GtkWidget*
create_aboutdialog (void)
{
  GtkWidget *aboutdialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *label2;
  GtkWidget *dialog_action_area4;
  GtkWidget *hbuttonbox3;
  GtkWidget *OK;

  aboutdialog = gtk_dialog_new ();
  gtk_widget_set_name (aboutdialog, "aboutdialog");
  gtk_object_set_data (GTK_OBJECT (aboutdialog), "aboutdialog", aboutdialog);
  gtk_window_set_title (GTK_WINDOW (aboutdialog), _("About"));
  gtk_window_set_policy (GTK_WINDOW (aboutdialog), TRUE, TRUE, FALSE);

  dialog_vbox4 = GTK_DIALOG (aboutdialog)->vbox;
  gtk_widget_set_name (dialog_vbox4, "dialog_vbox4");
  gtk_object_set_data (GTK_OBJECT (aboutdialog), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  label2 = gtk_label_new (_("PEOS Program\n\nProgrammer: Jigar Shah\nGUI Implimetor(s): Big Bang 1 Group"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (aboutdialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), label2, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);

  dialog_action_area4 = GTK_DIALOG (aboutdialog)->action_area;
  gtk_widget_set_name (dialog_action_area4, "dialog_action_area4");
  gtk_object_set_data (GTK_OBJECT (aboutdialog), "dialog_action_area4", dialog_action_area4);
  gtk_widget_show (dialog_action_area4);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area4), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox3, "hbuttonbox3");
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (aboutdialog), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (dialog_action_area4), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);

  OK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (OK, "OK");
  gtk_widget_ref (OK);
  gtk_object_set_data_full (GTK_OBJECT (aboutdialog), "OK", OK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), OK);
  GTK_WIDGET_SET_FLAGS (OK, GTK_CAN_DEFAULT);

  gtk_signal_connect_object (GTK_OBJECT (OK), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (aboutdialog));

  return aboutdialog;
}

GtkWidget*
create_inputdialog (gchar *string)
{
  GtkWidget *inputdialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox3;
  GtkWidget *vbox4;
  GtkWidget *deletelable;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbuttonbox4;
  GtkWidget *OK;
  GtkWidget *Cancel;

  inputdialog = gtk_dialog_new ();
  gtk_widget_set_name (inputdialog, "inputdialog");
  gtk_object_set_data (GTK_OBJECT (inputdialog), "inputdialog", inputdialog);
  gtk_window_set_title (GTK_WINDOW (inputdialog), _("Resource"));
  gtk_window_set_policy (GTK_WINDOW (inputdialog), TRUE, TRUE, FALSE);

  dialog_vbox5 = GTK_DIALOG (inputdialog)->vbox;
  gtk_widget_set_name (dialog_vbox5, "dialog_vbox5");
  gtk_object_set_data (GTK_OBJECT (inputdialog), "dialog_vbox5", dialog_vbox5);
  gtk_widget_show (dialog_vbox5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox3, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 30);

  deletelable = gtk_label_new (string);
  gtk_widget_set_name (deletelable, "deletelable");
  gtk_widget_ref (deletelable);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "deletelable", deletelable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (deletelable);
  gtk_box_pack_start (GTK_BOX (vbox4), deletelable, TRUE, FALSE, 0);

  entry1 = gtk_entry_new_with_max_length (256);
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox4), entry1, FALSE, FALSE, 0);

  dialog_action_area5 = GTK_DIALOG (inputdialog)->action_area;
  gtk_widget_set_name (dialog_action_area5, "dialog_action_area5");
  gtk_object_set_data (GTK_OBJECT (inputdialog), "dialog_action_area5", dialog_action_area5);
  gtk_widget_show (dialog_action_area5);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area5), 10);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox4, "hbuttonbox4");
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (dialog_action_area5), hbuttonbox4, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_END);

  OK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (OK, "OK");
  gtk_widget_ref (OK);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "OK", OK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), OK);
  GTK_WIDGET_SET_FLAGS (OK, GTK_CAN_DEFAULT);

  Cancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_set_name (Cancel, "Cancel");
  gtk_widget_ref (Cancel);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "Cancel", Cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), Cancel);
  GTK_WIDGET_SET_FLAGS (Cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (OK), "clicked",
                      GTK_SIGNAL_FUNC (on_OK_clicked),
                      NULL); 

  gtk_signal_connect_object (GTK_OBJECT (OK), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (inputdialog));
  gtk_signal_connect_object (GTK_OBJECT (Cancel), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (inputdialog));

  return inputdialog;
}

GtkWidget*
create_rebinddialog (gchar *string)
{
  GtkWidget *inputdialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox3;
  GtkWidget *vbox4;
  GtkWidget *deletelable;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbuttonbox4;
  GtkWidget *OK;
  GtkWidget *Cancel;

  inputdialog = gtk_dialog_new ();
  gtk_widget_set_name (inputdialog, "inputdialog");
  gtk_object_set_data (GTK_OBJECT (inputdialog), "inputdialog", inputdialog);
  gtk_window_set_title (GTK_WINDOW (inputdialog), _("Resource"));
  gtk_window_set_policy (GTK_WINDOW (inputdialog), TRUE, TRUE, FALSE);

  dialog_vbox5 = GTK_DIALOG (inputdialog)->vbox;
  gtk_widget_set_name (dialog_vbox5, "dialog_vbox5");
  gtk_object_set_data (GTK_OBJECT (inputdialog), "dialog_vbox5", dialog_vbox5);
  gtk_widget_show (dialog_vbox5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox3, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 30);

  deletelable = gtk_label_new (string);
  gtk_widget_set_name (deletelable, "deletelable");
  gtk_widget_ref (deletelable);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "deletelable", deletelable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (deletelable);
  gtk_box_pack_start (GTK_BOX (vbox4), deletelable, TRUE, FALSE, 0);

  entry1 = gtk_entry_new_with_max_length (256);
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox4), entry1, FALSE, FALSE, 0);

  dialog_action_area5 = GTK_DIALOG (inputdialog)->action_area;
  gtk_widget_set_name (dialog_action_area5, "dialog_action_area5");
  gtk_object_set_data (GTK_OBJECT (inputdialog), "dialog_action_area5", dialog_action_area5);
  gtk_widget_show (dialog_action_area5);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area5), 10);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox4, "hbuttonbox4");
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (dialog_action_area5), hbuttonbox4, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_END);

  OK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (OK, "OK");
  gtk_widget_ref (OK);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "OK", OK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), OK);
  GTK_WIDGET_SET_FLAGS (OK, GTK_CAN_DEFAULT);

  Cancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_set_name (Cancel, "Cancel");
  gtk_widget_ref (Cancel);
  gtk_object_set_data_full (GTK_OBJECT (inputdialog), "Cancel", Cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), Cancel);
  GTK_WIDGET_SET_FLAGS (Cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (OK), "clicked",
                      GTK_SIGNAL_FUNC (on_OK_clicked),
                      NULL);

  gtk_signal_connect_object (GTK_OBJECT (OK), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (inputdialog));
  gtk_signal_connect_object (GTK_OBJECT (Cancel), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (inputdialog));

  return inputdialog;
}

void set_sensitive (void)
{
  gtk_widget_set_sensitive (table[cur_pid].page.Next, peos_sense.next);
  gtk_widget_set_sensitive (table[cur_pid].page.Previous, peos_sense.prev);
  gtk_widget_set_sensitive (table[cur_pid].page.Start, peos_sense.start);
  gtk_widget_set_sensitive (table[cur_pid].page.Suspend, peos_sense.suspend);
  gtk_widget_set_sensitive (table[cur_pid].page.Finish, peos_sense.finish);
  gtk_widget_set_sensitive (table[cur_pid].page.Abort, peos_sense.abort);
}

void draw_tree(int i)
{
  gtk_widget_destroy(table[i].page.tree1);
  table[i].page.tree1 = create_task_tree(i);
  gtk_widget_set_name (table[i].page.tree1, "tree1");
  gtk_widget_ref (table[i].page.tree1);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "tree1", table[i].page.tree1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table[i].page.tree1);
  gtk_container_add (GTK_CONTAINER (table[i].page.viewport1), table[i].page.tree1);
}

void draw_text(xmlNode *action )
{
  gtk_widget_destroy(table[cur_pid].page.text1);
  table[cur_pid].page.text1 = action_detail(action);
  gtk_widget_set_name (table[cur_pid].page.text1, "text1");
  gtk_widget_ref (table[cur_pid].page.text1);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "text1", table[cur_pid].page.text1,
                           (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table[cur_pid].page.text1);
  gtk_container_add (GTK_CONTAINER (table[cur_pid].page.scrollwindow2), table[cur_pid].page.text1);
}

void redisplay_menu(void)
{
  gtk_widget_destroy (delmenu);

  delmenu = del_menu();
  gtk_widget_set_name (delmenu, "delmenu");
  gtk_widget_ref (delmenu);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "delmenu", delmenu,
                           (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delmenu);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (delete1), delmenu);
  gtk_menu_item_set_placement (GTK_MENU_ITEM (delete1), GTK_LEFT_RIGHT);

  gtk_widget_destroy (viewmenu);

  viewmenu = make_menu();
  gtk_widget_set_name (viewmenu, "viewmenu");
  gtk_widget_ref (viewmenu);
  gtk_object_set_data_full (GTK_OBJECT (Peos), "viewmenu", viewmenu,
                           (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewmenu);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view), viewmenu);
}

