#!/usr/bin/expect -f
#

# This expect script prints a list of the compiled process models the 
# that can be run to create process instances.
#
# Invoke as:
# expect -f list.exp host port user password

# Argument parsing.
if {$argc < 4} {
    puts "Usage: expect $argv0 host port user password" 
    exit
}

set host [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]


# Connect to PEOS server via telnet.
set timeout -1
spawn telnet $host $port
match_max 100000
# Look for response from telnet indicating connection established.
expect  "Escape*\r"

# We are connected; send login command to PEOS and wait for reply.
send -- "login $user $password\r"
expect  "100 login successful\r"

# Login successful; list compiled models by sending 'available' message.
send -- "list\r"

# Successful requests are acknowledged with "100" reply lines.  "500"
# indicates an error.  
expect {
    "100\[ \t\r\n\]" {
	# Expect puts the output from the server into the TCL array element
	# expect_out(buffer).  We can use this to extract the actions into 
	# a TCL list.
	
	# Split the output by lines.
	set lines [split $expect_out(buffer) "\n"]

	# Grab the process and action from each line.
	set models {}
	foreach l $lines {
	    # Regexp compares a string to a regular expression, and optionally
	    # extracts subexpressions into variables.   The following looks 
	    # for a regular expression consisting of the string "100-",
	    # followed by a subexpression (the process name) consisting of 
	    # any characters except a space, followed by a space.
	    # (See regexp(n) man page.)
	    if {[regexp "100-(\[^ \n\r\t\]+)\[ \n\r\t\]" $l dummy process action]==1} {
		lappend models $process
	    }
	}
	
	# Now print out the list of actions.
	puts "Processes: "
	foreach model $models {
	    puts stdout [format "%s " $model]
	}
	puts stdout ""
    }
    "500*\r" {
	puts stdout [format "Error processing list command: %s" $output(buffer)]
    }
}

# Exit PEOS session.
send -- "exit\r"
expect  "Connection closed by foreign host.\r"

# Wait for end of file from telnet before ending expect session.
expect eof
