CC=gcc
OBJECTS =login.o SMTP.o getcgivars.o interface.o smpsock.o strlib.o config.o

login.cgi:  $(OBJECTS)
	$(CC) -o login.cgi $(OBJECTS)

INSTALL_DIR=${HOME}/public_html

install: cp public_html/Login.html ${INSTALL_DIR} public_html/form.html ${INSTALL_DIR} cp public_html/BackGround.gif ${INSTALL_DIR} cp public_html/Commands.html ${INSTALL_DIR} cp public_html/Images ${INSTALL_DIR} cp public_html/Login.html ${INSTALL_DIR} cp public_html/Main.html ${INSTALL_DIR} cp public_html/P.E.O.S.apf ${INSTALL_DIR} cp public_html/Title.html ${INSTALL_DIR} cp public_html/WorkArea.html ${INSTALL_DIR} cp public_html/index.html ${INSTALL_DIR} cp public_html/laymanshelp.html ${INSTALL_DIR} cp public_html/sm_beachball.jpg ${INSTALL_DIR} cp public_html/techhelp.html ${INSTALL_DIR}


      
