#!/bin/csh -f 
#  Test script for the webui.cgi


setenv REQUEST_METHOD GET
set CGI = ~/peos/src/ui/web
setenv QUERY_STRING'username=ki&password=ki1&command=create&action=0'
webui.cgi
( echo login kirillk password 676046
sleep 1
echo list
sleep 1
echo available )| telnet milton 14523
                            
