#!/bin/sh
#
#Test script for Engine - runs 'timesheet' process.
#
#Mark Mastroieni - SCU - Summer 2002

HOST=linux103
PORT=14176

#NOTE: If a previous timesheet process has been started
#  but not finished, its state may be saved in files
#  pmlstate.dat, ".idx - and this script may not run
#  correctly!
rm pmlstate.dat pmlstate.idx  2>$O

set timeout 10

#without this, start 'PMLServer &' manually
#  before running 'testEngine'!
#(
#sleep 1
#echo "mmastroi" ; sleep 1 ; 
#echo "PWD" ; sleep 1 ; 
#echo "cd summer/peos/src/os/kernel/" ; sleep 1 ; 
#echo "PMLServer" ; sleep 1
#) | /usr/bin/telnet $HOST

(
echo "login Engine mark"; sleep 1 
#echo "list" ; sleep 1
echo "create timesheet"; sleep 2

#echo "help" ; sleep 1
#echo "sample" ; sleep 1
#echo "available" ; sleep 1

echo "run timesheet.001 get_card" ; sleep 1
#echo "running" ; sleep 1
echo "done timesheet.001 get_card" ; sleep 1

echo "run timesheet.001 enter_pay_period" ; sleep 1
echo "done timesheet.001 enter_pay_period" ; sleep 1

echo "run timesheet.001 fill_hours" ; sleep 1
echo "done timesheet.001 fill_hours" ; sleep 1

echo "run timesheet.001 fill_totals" ; sleep 1
echo "done timesheet.001 fill_totals" ; sleep 1

echo "run timesheet.001 sign_card" ; sleep 1
echo "done timesheet.001 sign_card" ; sleep 1

echo "run timesheet.001 approve_card" ; sleep 1
echo "done timesheet.001 approve_card" ; sleep 1

echo "run timesheet.001 turn_in" ; sleep 1
echo "done timesheet.001 turn_in" ; sleep 1

echo "logout"; sleep 2

) | /usr/bin/telnet $HOST $PORT | awk '$1==500{print "**ERROR:",$0}'

echo "If no '**ERROR...' message, Engine Passed!"