#!/bin/sh
#
#Test script for testEngine

HOST=linux.scudc.scu.edu
PORT=14176

#removes state information from previous
# runnings of this script...
rm -r Engine/

(
echo "login Engine mark"; sleep 1 
echo "list" ; sleep 1
echo "create timesheet"; sleep 2

echo "run timesheet.001 get_card" ; sleep 1
echo "done timesheet.001 get_card" ; sleep 1

echo "run timesheet.001 enter_pay_period" ; sleep 1
echo "done timesheet.001 enter_pay_period" ; sleep 1

echo "run timesheet.001 fill_hours" ; sleep 1
echo "done timesheet.001 fill_hours" ; sleep 1

echo "run timesheet.001 fill_totals" ; sleep 1
echo "done timesheet.001 fill_totals" ; sleep 1

echo "run timesheet.001 sign_card" ; sleep 1
echo "done timesheet.001 sign_card" ; sleep 1

echo "run timesheet.001 approve_card" ; sleep 1
echo "done timesheet.001 approve_card" ; sleep 1

echo "run timesheet.001 turn_in" ; sleep 1
echo "done timesheet.001 turn_in" ; sleep 1

echo "logout"; sleep 2

) | /usr/bin/telnet $HOST $PORT | awk '$1==500{print "**ERROR:",$0}'

